spring:
  cloud:
    gateway:
      routes:
      - id: microservico-um
        uri:  http://microservico-um:8080
        predicates:
        - Path=/microservico-um/**
  application:
    name: microservice-gateway
