spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: microservice-um
        uri:  http://microservice-um:8080
        predicates:
        - Path=/microservice-um/**
  application:
    name: microservice-gateway