spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: microservice-um
        uri:  http://microservico-um
        predicates:
        - Path=/microservico-um/**
  application:
    name: microservice-gateway
