spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: Microservice-um
        uri:  http://Microservice-um
        predicates:
        - Path=/microservice-um/**
  application:
    name: microservice-gateway